[package]
name = "card-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.18.2", features = ["full"] }

log = "0.4.17"
simple_logger = "2.1.0"
#env_logger = "0.9.0"

winit = "0.26.1"
wgpu = { version = "0.12.0", features = ["spirv"] }
shaderc = "0.8.0"
egui = "0.18.1"
egui-winit = "0.18.0"
